
#
# Module Manifest for Module 'Gitlab-API.psd1
#
# This manifest file is a PowerShell hashtable with all technical requirements for this module
# This module was autogenerated by ISESteroids (http://www.isesteroids.com)
#
# Generated: 2016-07-20
#

@{

# Module Loader File
RootModule = 'loader.psm1'

# Version Number
ModuleVersion = '0.4.1'

# Unique Module ID
GUID = '5a3fa905-b099-4165-a608-2e37306cf6b5'

# Module Author
Author = 'thijs de Meester'

# Company
CompanyName = 'tdemeester.nl'

# Copyright
Copyright = '(c) 2016 sys_host. All rights reserved.'

# Module Description
Description = 'Gitlab API functions'

# Minimum PowerShell Version Required
PowerShellVersion = '5.0'

# Name of Required PowerShell Host
PowerShellHostName = ''

# Minimum Host Version Required
PowerShellHostVersion = ''

# Minimum .NET Framework-Version
DotNetFrameworkVersion = ''

# Minimum CLR (Common Language Runtime) Version
CLRVersion = ''

# Processor Architecture Required (X86, Amd64, IA64)
ProcessorArchitecture = ''

# Required Modules (will load before this module loads)
RequiredModules = @()

# Required Assemblies
RequiredAssemblies = @()

# PowerShell Scripts (.ps1) that need to be executed before this module loads
ScriptsToProcess = @()

# Type files (.ps1xml) that need to be loaded when this module loads
TypesToProcess = @()

# Format files (.ps1xml) that need to be loaded when this module loads
FormatsToProcess = @()

# 
NestedModules = @()

# List of exportable functions
FunctionsToExport = '*'

# List of exportable cmdlets
CmdletsToExport = '*'

# List of exportable variables
VariablesToExport = '*'

# List of exportable aliases
AliasesToExport = '*'

# List of all modules contained in this module
ModuleList = @()

# List of all files contained in this module
FileList = @()

# Private data that needs to be passed to this module
PrivateData = ''

}