# DO NOT MODIFY THIS FILE!
# THIS FILE WAS AUTOGENERATED BY ISESTEROIDS AND WILL BE OVERWRITTEN WHEN YOU EXPORT FUNCTIONS TO THIS MODULE.

# USE THIS FILE FOR ADDITIONAL MODULE CODE. THIS FILE WILL NOT BE OVERWRITTEN
# WHEN NEW CONTENT IS PUBLISHED TO THIS MODULE:
. $PSScriptRoot\init.ps1


# LOADING ALL FUNCTION DEFINITIONS:

. $PSScriptRoot\Add-GitLabProjectStar.ps1
. $PSScriptRoot\Add-GitLabToken.ps1
. $PSScriptRoot\Get-GitlabConnect.ps1
. $PSScriptRoot\Get-GitLabProject.ps1
. $PSScriptRoot\Get-GitLabProjectEvents.ps1
. $PSScriptRoot\Get-GitLabProjectLabel.ps1
. $PSScriptRoot\Get-GitLabProjectMilestone.ps1
. $PSScriptRoot\Get-GitLabToken.ps1
. $PSScriptRoot\init.ps1
. $PSScriptRoot\Invoke-GitLabProjectArchive.ps1
. $PSScriptRoot\Invoke-GitLabProjectUnArchive.ps1
. $PSScriptRoot\Invoke-GitLabProjectFork.ps1
. $PSScriptRoot\New-GitlabProject.ps1
. $PSScriptRoot\New-GitLabProjectLabel.ps1
. $PSSCriptRoot\Register-GitLabProjectLabelSubscription.ps1
. $PSScriptRoot\Remove-GitLabProjectLabel
. $PSScriptRoot\Remove-GitLabProjectStar.ps1
. $PSScriptRoot\Remove-GitLabToken.ps1
. $PSScriptRoot\Set-GitlabProject.ps1
. $PSScriptRoot\Set-GitLabProjectLabel.ps1
. $PSScriptRoot\Set-GitLabToken.ps1
. $PSSCriptRoot\Unregister-GitLabProjectLabelSubscription.ps1