# DO NOT MODIFY THIS FILE!
# THIS FILE WAS AUTOGENERATED BY ISESTEROIDS AND WILL BE OVERWRITTEN WHEN YOU EXPORT FUNCTIONS TO THIS MODULE.

# USE THIS FILE FOR ADDITIONAL MODULE CODE. THIS FILE WILL NOT BE OVERWRITTEN
# WHEN NEW CONTENT IS PUBLISHED TO THIS MODULE:
. $PSScriptRoot\init.ps1


# LOADING ALL FUNCTION DEFINITIONS:

. $PSScriptRoot\Get-GitLabGroup.ps1
. $PSScriptRoot\Add-GitLabProjectStar.ps1
. $PSScriptRoot\Add-GitLabToken.ps1
. $PSScriptRoot\Approve-GitLabProjectMergeRequest.ps1
. $PSScriptRoot\Block-GitlabUser.ps1
. $PsScriptRoot\Compare-GitLabProjectRepositoryCommit.ps1
. $PSScriptRoot\Get-GitLabConnect.ps1
. $PSScriptRoot\Get-GitLabProject.ps1
. $PSScriptRoot\Get-GitLabProjectBranch.ps1
. $PSScriptRoot\Get-GitLabProjectEvents.ps1
. $PSScriptRoot\Get-GitLabProjectIssue.ps1
. $PSScriptRoot\Get-GitLabProjectIssueNote.ps1
. $PSScriptRoot\Get-GitLabProjectLabel.ps1
. $PSScriptRoot\Get-GitLabProjectMergeRequest.ps1
. $PSScriptRoot\Get-GitLabProjectMergeRequestCommits.ps1
. $PSScriptRoot\Get-GitLabProjectMergeRequestNote.ps1
. $PSScriptRoot\Get-GitLabProjectMilestone.ps1
. $PSScriptRoot\Get-GitLabProjectMilestoneIssues.ps1
. $PSScriptRoot\Get-GitLabProjectRepositoryArchive.ps1
. $PSScriptRoot\Get-GitLabProjectRepositoryCommit.ps1
. $PSScriptRoot\Get-GitLabProjectRepositoryCommitComment.ps1
. $PSScriptRoot\Get-GitLabProjectRepositoryCommitDiff.ps1
. $PSScriptRoot\Get-GitLabProjectRepositoryContributors.ps1
. $PSScriptRoot\Get-GitlabProjectRepositoryFile.ps1
. $PSScriptRoot\Get-GitLabProjectRepositoryFileRaw.ps1
. $PSScriptRoot\Get-GitLabProjectRepositoryTag.ps1
. $PSScriptRoot\Get-GitLabProjectRepositoryTree.ps1
. $PSScriptRoot\Get-GitLabToken.ps1
. $PSScriptRoot\Get-GitLabUser.ps1
. $PSScriptRoot\Invoke-GitLabProjectArchive.ps1
. $PSScriptRoot\Invoke-GitLabProjectUnArchive.ps1
. $PSScriptRoot\Invoke-GitLabProjectFork.ps1
. $PSScriptRoot\New-GitLabGroup.ps1
. $PSScriptRoot\New-GitLabProject.ps1
. $PSScriptRoot\New-GitlabProjectBranch.ps1
. $PSScriptRoot\New-GitLabProjectIssue.ps1
. $PSScriptRoot\New-GitLabProjectIssueNote.ps1
. $PSScriptRoot\New-GitLabProjectLabel.ps1
. $PSScriptRoot\New-GitLabProjectMergeRequest.ps1
. $PSScriptRoot\New-GitLabProjectMergeRequestNote.ps1
. $PSScriptRoot\New-GitLabProjectMilestone.ps1
. $PSScriptRoot\New-GitLabProjectRepositoryCommitComment.ps1
. $PSSCriptRoot\New-GitlabProjectRepositoryFile.ps1
. $PSScriptRoot\New-GitLabProjectRepositoryTag.ps1
. $PSScriptRoot\New-GitLabUser.ps1
. $PSScriptRoot\Protect-GitlabProjectBranch.ps1
. $PSSCriptRoot\Register-GitLabProjectLabelSubscription.ps1
. $PSScriptRoot\Remove-GitLabProjectLabel.ps1
. $PSSCriptRoot\Remove-GitLabProjectRepositoryFile.ps1
. $PSScriptRoot\Remove-GitLabProjectStar.ps1
. $PSScriptRoot\Remove-GitLabToken.ps1
. $PSScriptRoot\Set-GitlabGroup.ps1
. $PSScriptRoot\Set-GitlabProject.ps1
. $PSScriptRoot\Set-GitLabProjectIssue.ps1
. $PSScriptRoot\Set-GitLabProjectIssueNote.ps1
. $PSScriptRoot\Set-GitLabProjectLabel.ps1
. $PSScriptRoot\Set-GitLabProjectMergeRequest.ps1
. $PSScriptRoot\Set-GitLabProjectMilestone.ps1
. $PSScriptRoot\Set-GitLabProjectRepositoryFile.ps1
. $PSScriptRoot\Set-GitLabProjectRepositoryTagReleaseNotes.ps1
. $PSScriptRoot\Set-GitLabToken.ps1
. $PSScriptRoot\Set-GitLabUser.ps1
. $PSScriptRoot\Unblock-GitlabUser.ps1
. $PSScriptRoot\Unprotect-GitlabProjectBranch.ps1
. $PSSCriptRoot\Unregister-GitLabProjectLabelSubscription.ps1
. $PSScriptRoot\Update-GitLabProjectMirror.ps1